export const types = {
  LOGIN: "LOGIN",
  LOGOUT: "LOGOUT",
  NOTICE: "NOTICE",
  NOTICETYPE: "NOTICETYPE",
  MACHINE: "MACHINE",
  CAUSE: "CAUSE",
  OBJECT: "OBJECT",
  SYMTOM: "SYMTOM",
  GROUPCODE: "GROUPCODE",
};
